# Generated by Django 3.1.7 on 2021-02-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Cod.')),
                ('alun_nome', models.CharField(db_column='alumn_nome', default='', max_length=150, verbose_name='Nome Completo')),
                ('alun_email', models.EmailField(blank=True, db_column='alun_email', default='', max_length=254, null=True, verbose_name='Email')),
                ('alun_telefone', models.CharField(blank=True, db_column='alun_telefone', default='', max_length=12, null=True, verbose_name='Telefone')),
                ('alun_whatsapp', models.CharField(blank=True, db_column='alun_whatsapp', default='', max_length=12, null=True, verbose_name='whatsapp ')),
                ('alun_endereco', models.CharField(blank=True, db_column='alun-endereço', default='', max_length=150, null=True, verbose_name='Endereço')),
                ('alun_bairro', models.CharField(blank=True, db_column='alun_bairro', default='', max_length=150, null=True, verbose_name='Bairro')),
                ('alun_cidade', models.CharField(blank=True, db_column='alun_cidade', default='', max_length=150, null=True, verbose_name='Cidade')),
                ('alun_estado', models.CharField(blank=True, db_column='alun_estado', default='', max_length=150, null=True, verbose_name='Estado')),
                ('alun_datetime_inclusao', models.DateTimeField(auto_now_add=True, max_length=50, null=True, verbose_name='Data/Hora Inclusão')),
                ('alun_datetime_alteracao', models.DateTimeField(auto_now=True, max_length=50, null=True, verbose_name='Data/Hora Alteração')),
            ],
        ),
    ]
