# Generated by Django 3.1.7 on 2021-03-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20210227_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='alun_datetime_alteracao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='alun_datetime_inclusao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='alun_estado',
        ),
    ]
