# Generated by Django 3.1.7 on 2021-03-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('aluno', '0003_auto_20210301_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='alun_fk_disc',
            field=models.ForeignKey(blank=True, db_column='alun_fk_disc', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_rel_disc', to='disciplinas.disciplinas', verbose_name='Discplinas'),
        ),
    ]
