# Generated by Django 3.1.7 on 2021-03-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_aluno_alun_fk_disc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='alun_bairro',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='alun_endereco',
        ),
    ]
