# Generated by Django 3.1.7 on 2021-03-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_auto_20210301_1912'),
        ('aluno', '0005_auto_20210301_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='alun_fk_disc',
            field=models.ForeignKey(blank=True, db_column='alun_fk_disc', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_rel_disc', to='disciplinas.disciplinas', verbose_name='Disciplinas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='alun_nome',
            field=models.CharField(db_column='alun_nome', default='', max_length=150, verbose_name='Nome Completo'),
        ),
    ]
