# Generated by Django 3.1.7 on 2021-03-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Cod.')),
                ('disc_nome', models.CharField(db_column='disc_nome', default='', max_length=150, verbose_name='Nome da disciplina')),
            ],
        ),
    ]
