# Generated by Django 3.1.7 on 2021-03-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='disciplinas',
            table='disciplinas',
        ),
    ]
